name: CI
# https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#concurrency
# https://docs.github.com/en/developers/webhooks-and-events/events/github-event-types#pullrequestevent
concurrency:
  group: ${{ github.workflow }}-${{ github.event.number }}-${{ github.event.type }}
  cancel-in-progress: true

on:
  push:
  pull_request:
  schedule:
    # Every Saturday at midnight UTC
    - cron: '0 0 * * 6'


jobs:
  satpy_compat:
    name: Check Compatibility
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 flake8-docstrings flake8-debugger flake8-bugbear pyorbital

      - name: Install Plugin
        run: |
          pip install -e .
          pip install --no-deps -U git+https://github.com/wjsharpe/satpy.git

      - name: Run linting
        run: |
          flake8 satpy_viirs_l2/
